server:
 port: 8080   #As default port is 8080 in Springboot, can change here if needed.

 error: 
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
 
#servlet:
# context-path: /api/v0   To define a new path



spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/my_db
  username: new_user
  password: new_passw
  driver-class-name: org.postgresql.Driver
  
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   properties:
    '[hibernate.format_sql]': true
 
logging:
 file:
  name: logs/studentapp.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]': WARN
  '[org.hibernate]': INFO
  '[com.neb]': DEBUG
  
  
